=== nguyenhoangthanhlong1996/Tai-lieu-mon-hoc/Cong nghe XML va Ung dung/Quiz07_E1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="members">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="member" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="([a-zA-Z]+([a-zA-Z]*|\s[a-zA-Z]+))+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="yearsOfMembership" type="xs:nonNegativeInteger"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== nguyenhoangthanhlong1996/Tai-lieu-mon-hoc/Cong nghe XML va Ung dung/Quiz07_E1.xml
<?xml version="1.0" encoding="UTF-8"?>
<members xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Quiz07_E1.xsd">
    <member>
        <name>Chris Smith</name>
        <yearsOfMembership>4</yearsOfMembership>
    </member>
    <member>
        <name>Judi Zimmerman</name>
        <yearsOfMembership>5</yearsOfMembership>
    </member>
    <member>
        <name>Michael Calder</name>
        <yearsOfMembership>3</yearsOfMembership>
    </member>
</members>
